### ISSUE TITLE
Support local plugins

### ISSUE THREAD

**Issue by desyncr** [desyncr/zpm-zsh#2]
`zpm` should be able to install plugins from local path as well as github urls:

    zpm "/path/to/local/plugin"   # /path/to/local/plugin
    zpm "remote/plugin"           # github.com/remote/plugin.git

**Comment by fennecdjay** [comment]
Do you think the local plugin path has to be absolute ?
If not, I think the following behavior would address both #2 and #5:
  *  try to open path as regular file
      *  on success treat path as a local plugin, else
  *  if path contains only one slash
       *  host is github, else
  *  treat path as any git host

**Comment by fennecdjay** [comment]
What is the intented behavior for local plugin?
is it enough add an entry to *~/.zpm/.plugin_list*?

**Comment by desyncr** [comment]
@fennecdjay Yes, path should be absolute, and the behavior should be the same for both, only there is no need for cloning/updating.

**Comment by desyncr** [comment]
Done! Thank for your work @fennecdjay !
