### ISSUE TITLE
Update fpath and/or PATH

### ISSUE THREAD

**Issue by desyncr** [desyncr/zpm-zsh#3]
Generated `~/.zpm-init.zsh` should add entries to `fpath` and/or `PATH`. This is necessary for plugins installing functions to `fpath` or executables to `PATH`. Example:

`~/.zpm-init.zsh`:

    fpath+=(/path/to/plugin /path/to/other/plugin)

**Comment by fennecdjay** [comment]
Does it need an entry point or just the path?

**Comment by fennecdjay** [comment]
```sh
cat ~/.zpm-init.zsh
source /home/user/.zpm/plugins/zsh-users/zsh-autosuggestions/zsh-autosuggestions.zsh
fpath+=/home/user/.zpm/plugins/zsh-users/zsh-autosuggestions/
autoload -Uz compinit; compinit -iCd $HOME/.zcompdump
```
would that be OK?

**Comment by desyncr** [comment]
@fennecdjay Yeah, that would work just fine!

**Comment by fennecdjay** [comment]
OK, making a PR.

**Comment by fennecdjay** [comment]
So If you don't mind, I'll double-check  [1182fa1](https://github.com/fennecdjay/zpm-zsh/commit/1192fa11c04fc9553b60f528ebd8f31d24d7532b) and push it to desyncr/master.
I'm glad you invited me, thank you.

**Comment by fennecdjay** [comment]
Would the same aply for PATH?

**Comment by desyncr** [comment]
@fennecdjay I'd like to review it and once approved then you should be free to merge.

**Comment by fennecdjay** [comment]
Great! thanks.

**Comment by desyncr** [comment]
@fennecdjay BTW you should create a PR for review, then we'll follow the usual workflow.

**Comment by fennecdjay** [comment]
Done. see #15

**Comment by fennecdjay** [comment]
Also merged upstream.
I hope it does not mess with anything.
